spring.application.name=ProductsMicroService
##serverport in 0, means that when de app up, will start in a random port number
server.port=0
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
##Secure that all brokers store the message
spring.kafka.producer.acks=all

##Retries and time backoff
#spring.kafka.producer.properties.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=1000

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000
#spring.kafka.producer.properties.max.block.ms=120000

spring.kafka.producer.properties.max.in.fligth.requests.per.connection=5

##Kafka Config
app.kafka.product-created-topic=product-created-events-topic
app.kafka.topic2=topic2
